# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

#reward_comment:
wechatpay: /wechatpay.jpg
alipy: /alipay.jpg

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: false

social: 
  zhihu: https://www.zhihu.com/people/hao-hao-79-7-93

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
Zhihu: zhihu
google_plus:
fb_admins:
fb_app_id:
